
- name: Pull Docker image of all services
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  tasks:
      - name: Pull his service. 
        shell: | 
          eval $(minikube docker-env)
          docker pull nishu839/his-service:1.0
          docker tag nishu839/his-service:1.0 his-service:1.0
          docker rmi nishu839/his-service:1.0
      - name: Pull cms service. 
        shell: | 
          eval $(minikube docker-env)
          docker pull nishu839/cms-service:1.0
          docker tag nishu839/cms-service:1.0 cms-service:1.0
          docker rmi nishu839/cms-service:1.0

      - name: Pull admin service. 
        shell: | 
          eval $(minikube docker-env)
          docker pull nishu839/admin-service:1.0
          docker tag nishu839/admin-service:1.0 admin-service:1.0
          docker rmi nishu839/admin-service:1.0
          
      - name: Pull patient service. 
        shell: | 
          eval $(minikube docker-env)
          docker pull nishu839/patient-service:1.0
          docker tag nishu839/patient-service:1.0 patient-service:1.0
          docker rmi nishu839/patient-service:1.0
          
      - name: Pull his front end. 
        shell: | 
          eval $(minikube docker-env)
          docker pull nishu839/his-frontend-k8s:1.0
          docker tag nishu839/his-frontend-k8s:1.0 his-frontend-k8s:1.0
          docker rmi nishu839/his-frontend-k8s:1.0
            
      - name: Pull patient front end. 
        shell: | 
          eval $(minikube docker-env)
          docker pull nishu839/patient-frontend-k8s:1.0
          docker tag nishu839/patient-frontend-k8s:1.0 patient-frontend-k8s:1.0
          docker rmi nishu839/patient-frontend-k8s:1.0
           
      - name: Run kubectl commands for yml files of HIS Backend
        shell: | 
          eval $(minikube docker-env)
          cd HIS/backend/
          kubectl apply -f mysql-secret.yaml
          kubectl apply -f mysql-configMap.yaml 
          kubectl apply -f db-deployment.yaml 
          kubectl apply -f app-deployment.yaml
          
      - name: Run kubectl commands for yml files of admin services Backend
        shell: | 
          eval $(minikube docker-env)
          cd Central/admin/
          kubectl apply -f mysql-secret.yaml
          kubectl apply -f mysql-configMap.yaml 
          kubectl apply -f db-deployment.yaml 
          kubectl apply -f app-deployment.yaml
          
      - name: Run kubectl commands for yml files of cms services Backend
        shell: | 
          eval $(minikube docker-env)
          cd Central/cms/
          kubectl apply -f mysql-secret.yaml
          kubectl apply -f mysql-configMap.yaml 
          kubectl apply -f db-deployment.yaml 
          kubectl apply -f app-deployment.yaml   
          
      - name: Run kubectl commands for yml files of Patient services Backend
        shell: | 
          eval $(minikube docker-env)
          cd Patient/backend/
          kubectl apply -f mysql-secret.yaml
          kubectl apply -f mysql-configMap.yaml 
          kubectl apply -f db-deployment.yaml 
          kubectl apply -f app-deployment.yaml 
          
      - name: Run kubectl commands for yml files of Patient Frontend
        shell: | 
          eval $(minikube docker-env)
          cd Patient/frontend/
          kubectl apply -f patient-frontend-app.yaml
          kubectl apply -f patient-app-ingress.yaml 
        
      - name: Run kubectl commands for yml files of HIS Frontend
        shell: | 
          eval $(minikube docker-env)
          cd HIS/frontend/
          kubectl apply -f his-frontend-app.yaml
          kubectl apply -f his-app-ingress.yaml
          
#       - name: Delete all the none named images. 
#         shell: | 
#           eval $(minikube docker-env)
#           docker images | awk '$1 == "<none>" {print $3}' | xargs -I {} docker rmi -f {}
                   
 



   

