- name: Deploy all services to Minikube
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3

    images:
      - nishu839/his-service:1.0
      - nishu839/cms-service:1.0
      - nishu839/admin-service:1.0
      - nishu839/patient-service:1.0
      - nishu839/his-frontend-k8s:1.0
      - nishu839/patient-frontend-k8s:1.0

  tasks:

    # 🔽 Pull + load images into Minikube
    - name: Pull and load Docker images into Minikube
      shell: |
        docker pull {{ item }}
        minikube image load {{ item }}
      loop: "{{ images }}"

    # 🔽 HIS Backend
    - name: Deploy HIS Backend
      shell: |
        kubectl apply -f mysql-secret.yaml
        kubectl apply -f mysql-configMap.yaml
        kubectl apply -f db-deployment.yaml
        kubectl apply -f app-deployment.yaml
      args:
        chdir: /var/lib/jenkins/workspace/HOSPITAL-WebAPP/SPE-HISApp-SERVICE/target/classes/
      environment:
        KUBECONFIG: "{{ lookup('env','HOME') }}/.kube/config"
    
          # 🔽 Admin Backend
    - name: Deploy Admin Backend
      shell: |
        kubectl apply -f mysql-secret.yaml
        kubectl apply -f mysql-configMap.yaml
        kubectl apply -f db-deployment.yaml
        kubectl apply -f app-deployment.yaml
      args:
        chdir: /var/lib/jenkins/workspace/MedWeb-CentralServices/SPE-ADMIN-SERVICE/target/classes/
      environment:
        KUBECONFIG: "{{ lookup('env','HOME') }}/.kube/config"

    # 🔽 CMS Backend
    - name: Deploy CMS Backend
      shell: |
        kubectl apply -f mysql-secret.yaml
        kubectl apply -f mysql-configMap.yaml
        kubectl apply -f db-deployment.yaml
        kubectl apply -f app-deployment.yaml
      args:
        chdir: /var/lib/jenkins/workspace/MedWeb-CentralServices/SPE-CMS-SERVICE/target/classes/
      environment:
        KUBECONFIG: "{{ lookup('env','HOME') }}/.kube/config"

    # 🔽 Patient Backend
    - name: Deploy Patient Backend
      shell: |
        kubectl apply -f mysql-secret.yaml
        kubectl apply -f mysql-configMap.yaml
        kubectl apply -f db-deployment.yaml
        kubectl apply -f app-deployment.yaml
      args:
        chdir: /var/lib/jenkins/workspace/PatientApp/SPE-PatientApp-SERVICE/target/classes/
      environment:
        KUBECONFIG: "{{ lookup('env','HOME') }}/.kube/config"

    # 🔽 Patient Frontend
    - name: Deploy Patient Frontend
      shell: |
        kubectl apply -f patient-frontend-app.yaml
        kubectl apply -f patient-app-ingress.yaml
      args:
        chdir: /var/lib/jenkins/workspace/PatientApp/SPE-PatientApp-FRONTEND/
      environment:
        KUBECONFIG: "{{ lookup('env','HOME') }}/.kube/config"

    # 🔽 HIS Frontend
    - name: Deploy HIS Frontend
      shell: |
        kubectl apply -f his-frontend-app.yaml
        kubectl apply -f his-app-ingress.yaml
      args:
        chdir: /var/lib/jenkins/workspace/HOSPITAL-WebAPP/SPE-HISApp-FRONTEND/
      environment:
        KUBECONFIG: "{{ lookup('env','HOME') }}/.kube/config"    
